
import os
import logging
from pathlib import Path
from typing import List, Dict, Any, Optional
from llmware.parsers.records import Block

logger = logging.getLogger(__name__)

def process_parser_output(file_path: Path) -> List[Block]:
    """
    Reads the text file output from C parsers and converts to Blocks.

    Args:
        file_path: Path to the output file generated by the C library.

    Returns:
        List[Block]: A list of parsed blocks.
    """
    if not file_path.exists():
        logger.warning(f"Parser output file not found: {file_path}")
        return []

    default_keys = [
        "block_ID", "doc_ID", "content_type", "file_type", "master_index", "master_index2",
        "coords_x", "coords_y", "coords_cx", "coords_cy", "author_or_speaker", "modified_date",
        "created_date", "creator_tool", "added_to_collection", "file_source",
        "table", "external_files", "text", "header_text", "text_search",
        "user_tags", "special_field1", "special_field2", "special_field3", "graph_status", "dialog"
    ]

    blocks: List[Block] = []

    try:
        with open(file_path, "r", encoding="utf-8-sig", errors="ignore") as f:
            content = f.read()
    except Exception as e:
        logger.error(f"Error reading parser output file: {e}")
        return []

    # Split by the C-parser defined delimiter
    raw_blocks = content.split("<END_BLOCK>\n")

    for raw_block in raw_blocks:
        if not raw_block.strip():
            continue

        block_data = {}
        lines = raw_block.split("\n<")

        for line in lines:
            for key in default_keys:
                key_marker = f"{key}>: "

                # Check for marker (handling start of file case)
                if line.startswith(key_marker) or line.startswith(f"<{key_marker}"):
                    clean_marker = key_marker
                    if line.startswith("<"):
                         clean_marker = f"<{key_marker}"

                    value = line[len(clean_marker):].strip()
                    if value.endswith(","):
                        value = value[:-1]

                    block_data[key] = value
                    break

        # Map to Block dataclass
        if "text" in block_data:
            # Helper for safe int conversion
            def get_int(k):
                try:
                    val = block_data.get(k, 0)
                    return int(val) if str(val).isdigit() else 0
                except: return 0

            block = Block(
                text=block_data.get("text", ""),
                doc_id=get_int("doc_ID"),
                block_id=get_int("block_ID"),
                file_source=block_data.get("file_source", ""),
                content_type=block_data.get("content_type", "text"),
                file_type=block_data.get("file_type", "unknown"),
                master_index=get_int("master_index"),
                master_index2=get_int("master_index2"),
                coords_x=get_int("coords_x"),
                coords_y=get_int("coords_y"),
                coords_cx=get_int("coords_cx"),
                coords_cy=get_int("coords_cy"),
                author_or_speaker=block_data.get("author_or_speaker", ""),
                modified_date=block_data.get("modified_date", ""),
                created_date=block_data.get("created_date", ""),
                creator_tool=block_data.get("creator_tool", ""),
                added_to_collection=block_data.get("added_to_collection", ""),
                table=block_data.get("table", ""),
                external_files=block_data.get("external_files", ""),
                header_text=block_data.get("header_text", ""),
                text_search=block_data.get("text_search", ""),
                user_tags=block_data.get("user_tags", ""),
                special_field1=block_data.get("special_field1", ""),
                special_field2=block_data.get("special_field2", ""),
                special_field3=block_data.get("special_field3", ""),
                graph_status=block_data.get("graph_status", "false"),
                dialog=block_data.get("dialog", "false")
            )
            blocks.append(block)

    return blocks
